#!/bin/bash

export JDK8_PATH=$OPENSHIFT_DATA_DIR/jdk1.8.0_05/bin
export PATH=$JDK8_PATH:$PATH
export JAVA_HOME="$OPENSHIFT_DATA_DIR/jdk/jdk1.8.0_05"

if [ ! -d "$JDK8_PATH" ]; then
	wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u5-b13/jdk-8u5-linux-x64.tar.gz
	tar -zxf jdk-8u5-linux-x64.tar.gz
fi


# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080 


# loads $PLAY_PARAMS
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
	exit $?
fi

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}play.log"

chmod +x ${OPENSHIFT_REPO_DIR}target/universal/stage/bin/play-with-angular-requirejs

APP_COMMAND="${OPENSHIFT_REPO_DIR}target/universal/stage/bin/play-with-angular-requirejs $PLAY_PARAMS "\
"-Dhttp.port=${OPENSHIFT_DIY_PORT} "\
"-Dhttp.address=${OPENSHIFT_DIY_IP} "\
"-Dconfig.resource=openshift.conf"

echo $APP_COMMAND &>> $LOG_FILE
nohup bash -c "${APP_COMMAND} &>> ${LOG_FILE} 2>&1" &> /dev/null &
